//私人FM
export default {
    "popAdjust": false,
    "data": [
        {
            "name": "アスノヨゾラ哨戒班。明日的夜空哨戒班（Cover IA）",
            "id": 469719260,
            "position": 2,
            "alias": [],
            "status": 0,
            "fee": 0,
            "copyrightId": 0,
            "disc": "1",
            "no": 2,
            "artists": [
                {
                    "name": "Akie秋绘",
                    "id": 12184145,
                    "picId": 0,
                    "img1v1Id": 0,
                    "briefDesc": "",
                    "picUrl": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                    "img1v1Url": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                    "albumSize": 0,
                    "alias": [],
                    "trans": "",
                    "musicSize": 0,
                    "topicPerson": 0
                },
                {
                    "name": "夏璃夜",
                    "id": 12236114,
                    "picId": 0,
                    "img1v1Id": 0,
                    "briefDesc": "",
                    "picUrl": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                    "img1v1Url": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                    "albumSize": 0,
                    "alias": [],
                    "trans": "",
                    "musicSize": 0,
                    "topicPerson": 0
                }
            ],
            "album": {
                "name": "春雫。2017",
                "id": 35271163,
                "type": "专辑",
                "size": 2,
                "picId": 109951162875736180,
                "blurPicUrl": "http://p3.music.126.net/aY9LN0OfVrkh5LO1chFQig==/109951162875736171.jpg",
                "companyId": 0,
                "pic": 109951162875736180,
                "picUrl": "http://p4.music.126.net/aY9LN0OfVrkh5LO1chFQig==/109951162875736171.jpg",
                "publishTime": 1489311063474,
                "description": "",
                "tags": "",
                "company": null,
                "briefDesc": "",
                "artist": {
                    "name": "",
                    "id": 0,
                    "picId": 0,
                    "img1v1Id": 0,
                    "briefDesc": "",
                    "picUrl": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                    "img1v1Url": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                    "albumSize": 0,
                    "alias": [],
                    "trans": "",
                    "musicSize": 0,
                    "topicPerson": 0
                },
                "songs": [],
                "alias": [],
                "status": 0,
                "copyrightId": 0,
                "commentThreadId": "R_AL_3_35271163",
                "artists": [
                    {
                        "name": "Akie秋绘",
                        "id": 12184145,
                        "picId": 0,
                        "img1v1Id": 0,
                        "briefDesc": "",
                        "picUrl": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                        "img1v1Url": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                        "albumSize": 0,
                        "alias": [],
                        "trans": "",
                        "musicSize": 0,
                        "topicPerson": 0
                    }
                ],
                "subType": "混音版",
                "transName": null,
                "mark": 0,
                "picId_str": "109951162875736171"
            },
            "starred": false,
            "popularity": 100,
            "score": 100,
            "starredNum": 0,
            "duration": 234847,
            "playedNum": 0,
            "dayPlays": 0,
            "hearTime": 0,
            "ringtone": null,
            "crbt": null,
            "audition": null,
            "copyFrom": "",
            "commentThreadId": "R_SO_4_469719260",
            "rtUrl": null,
            "ftype": 0,
            "rtUrls": [],
            "copyright": 0,
            "transName": null,
            "sign": null,
            "mark": 0,
            "noCopyrightRcmd": null,
            "rtype": 0,
            "rurl": null,
            "mvid": 0,
            "bMusic": {
                "name": null,
                "id": 1297866599,
                "size": 3761676,
                "extension": "mp3",
                "sr": 44100,
                "dfsId": 0,
                "bitrate": 128000,
                "playTime": 234847,
                "volumeDelta": -4500
            },
            "mp3Url": null,
            "hMusic": {
                "name": null,
                "id": 1297866597,
                "size": 9404125,
                "extension": "mp3",
                "sr": 44100,
                "dfsId": 0,
                "bitrate": 320000,
                "playTime": 234847,
                "volumeDelta": -8800
            },
            "mMusic": {
                "name": null,
                "id": 1297866598,
                "size": 5642493,
                "extension": "mp3",
                "sr": 44100,
                "dfsId": 0,
                "bitrate": 192000,
                "playTime": 234847,
                "volumeDelta": -6300
            },
            "lMusic": {
                "name": null,
                "id": 1297866599,
                "size": 3761676,
                "extension": "mp3",
                "sr": 44100,
                "dfsId": 0,
                "bitrate": 128000,
                "playTime": 234847,
                "volumeDelta": -4500
            },
            "privilege": {
                "id": 469719260,
                "fee": 0,
                "payed": 0,
                "st": 0,
                "pl": 320000,
                "dl": 320000,
                "sp": 7,
                "cp": 1,
                "subp": 1,
                "cs": false,
                "maxbr": 320000,
                "fl": 320000,
                "toast": false,
                "flag": 128,
                "preSell": false,
                "playMaxbr": 320000,
                "downloadMaxbr": 320000,
                "freeTrialPrivilege": {
                    "resConsumable": false,
                    "userConsumable": false
                },
                "chargeInfoList": [
                    {
                        "rate": 128000,
                        "chargeUrl": null,
                        "chargeMessage": null,
                        "chargeType": 0
                    },
                    {
                        "rate": 192000,
                        "chargeUrl": null,
                        "chargeMessage": null,
                        "chargeType": 0
                    },
                    {
                        "rate": 320000,
                        "chargeUrl": null,
                        "chargeMessage": null,
                        "chargeType": 0
                    },
                    {
                        "rate": 999000,
                        "chargeUrl": null,
                        "chargeMessage": null,
                        "chargeType": 1
                    }
                ]
            },
            "alg": "itembased"
        },
        {
            "name": "Find the way",
            "id": 1301574789,
            "position": 9,
            "alias": [
                "原曲：東方妖々夢より  \"東方妖々夢 〜 Ancient Temple\""
            ],
            "status": 0,
            "fee": 0,
            "copyrightId": 663018,
            "disc": "1",
            "no": 2,
            "artists": [
                {
                    "name": "舞花",
                    "id": 12096262,
                    "picId": 0,
                    "img1v1Id": 0,
                    "briefDesc": "",
                    "picUrl": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                    "img1v1Url": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                    "albumSize": 0,
                    "alias": [],
                    "trans": "",
                    "musicSize": 0,
                    "topicPerson": 0
                },
                {
                    "name": "Vivienne",
                    "id": 29270658,
                    "picId": 0,
                    "img1v1Id": 0,
                    "briefDesc": "",
                    "picUrl": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                    "img1v1Url": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                    "albumSize": 0,
                    "alias": [],
                    "trans": "",
                    "musicSize": 0,
                    "topicPerson": 0
                }
            ],
            "album": {
                "name": "Darkness Brightness",
                "id": 72301797,
                "type": "专辑",
                "size": 14,
                "picId": 109951163461800780,
                "blurPicUrl": "http://p4.music.126.net/aF4u2r8Z8j1z9Zp-uPB6Qw==/109951163461800786.jpg",
                "companyId": 0,
                "pic": 109951163461800780,
                "picUrl": "http://p4.music.126.net/aF4u2r8Z8j1z9Zp-uPB6Qw==/109951163461800786.jpg",
                "publishTime": 1533830400007,
                "description": "",
                "tags": "",
                "company": "C94",
                "briefDesc": "",
                "artist": {
                    "name": "",
                    "id": 0,
                    "picId": 0,
                    "img1v1Id": 0,
                    "briefDesc": "",
                    "picUrl": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                    "img1v1Url": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                    "albumSize": 0,
                    "alias": [],
                    "trans": "",
                    "musicSize": 0,
                    "topicPerson": 0
                },
                "songs": [],
                "alias": [],
                "status": 0,
                "copyrightId": 663018,
                "commentThreadId": "R_AL_3_72301797",
                "artists": [
                    {
                        "name": "FELT",
                        "id": 19460,
                        "picId": 0,
                        "img1v1Id": 0,
                        "briefDesc": "",
                        "picUrl": "http://p4.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                        "img1v1Url": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                        "albumSize": 0,
                        "alias": [],
                        "trans": "",
                        "musicSize": 0,
                        "topicPerson": 0
                    }
                ],
                "subType": "录音室版",
                "transName": null,
                "mark": 0,
                "picId_str": "109951163461800786"
            },
            "starred": false,
            "popularity": 95,
            "score": 95,
            "starredNum": 0,
            "duration": 227693,
            "playedNum": 0,
            "dayPlays": 0,
            "hearTime": 0,
            "ringtone": null,
            "crbt": null,
            "audition": null,
            "copyFrom": "",
            "commentThreadId": "R_SO_4_1301574789",
            "rtUrl": null,
            "ftype": 0,
            "rtUrls": [],
            "copyright": 0,
            "transName": null,
            "sign": null,
            "mark": 0,
            "noCopyrightRcmd": null,
            "rtype": 0,
            "rurl": null,
            "mvid": 0,
            "bMusic": {
                "name": null,
                "id": 3647037952,
                "size": 3644230,
                "extension": "mp3",
                "sr": 44100,
                "dfsId": 0,
                "bitrate": 128000,
                "playTime": 227693,
                "volumeDelta": -2
            },
            "mp3Url": null,
            "hMusic": {
                "name": null,
                "id": 3647037950,
                "size": 9110509,
                "extension": "mp3",
                "sr": 44100,
                "dfsId": 0,
                "bitrate": 320000,
                "playTime": 227693,
                "volumeDelta": -2
            },
            "mMusic": {
                "name": null,
                "id": 3647037951,
                "size": 5466323,
                "extension": "mp3",
                "sr": 44100,
                "dfsId": 0,
                "bitrate": 192000,
                "playTime": 227693,
                "volumeDelta": -2
            },
            "lMusic": {
                "name": null,
                "id": 3647037952,
                "size": 3644230,
                "extension": "mp3",
                "sr": 44100,
                "dfsId": 0,
                "bitrate": 128000,
                "playTime": 227693,
                "volumeDelta": -2
            },
            "privilege": {
                "id": 1301574789,
                "fee": 0,
                "payed": 0,
                "st": 0,
                "pl": 320000,
                "dl": 999000,
                "sp": 7,
                "cp": 1,
                "subp": 1,
                "cs": false,
                "maxbr": 999000,
                "fl": 320000,
                "toast": false,
                "flag": 256,
                "preSell": false,
                "playMaxbr": 999000,
                "downloadMaxbr": 999000,
                "freeTrialPrivilege": {
                    "resConsumable": false,
                    "userConsumable": false
                },
                "chargeInfoList": [
                    {
                        "rate": 128000,
                        "chargeUrl": null,
                        "chargeMessage": null,
                        "chargeType": 0
                    },
                    {
                        "rate": 192000,
                        "chargeUrl": null,
                        "chargeMessage": null,
                        "chargeType": 0
                    },
                    {
                        "rate": 320000,
                        "chargeUrl": null,
                        "chargeMessage": null,
                        "chargeType": 0
                    },
                    {
                        "rate": 999000,
                        "chargeUrl": null,
                        "chargeMessage": null,
                        "chargeType": 1
                    }
                ]
            },
            "alg": "itembased"
        }
    ],
    "code": 200
};